# Configuration options for dependency updates
# See: https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
# To make it work install: https://github.com/marketplace/dependabot-preview

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci:"

  # Maintain Go dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci:"

  # Maintain Go dependencies for API
  - package-ecosystem: "gomod"
    directory: "/pkg/apis"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci:"
